services:
  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - crewai-network

  flask_orchestrator:
    build:
      context: .
      dockerfile: flask_orchestrator/Dockerfile
    container_name: flask_orchestrator
    ports:
      - "5000:5000"
    env_file:
      - flask_orchestrator/.env.flask_orchestrator
    depends_on:
      - redis
    networks:
      - crewai-network

  preprocess_worker:
    build:
      context: .
      dockerfile: workers/preprocess/Dockerfile
    container_name: preprocess_worker
    env_file:
      - workers/preprocess/.env.preprocess
    depends_on:
      - redis
      - flask_orchestrator
    networks:
      - crewai-network

networks:
  crewai-network:
    driver: bridge
