FROM python:3.11-slim

WORKDIR /app

# Install dependencies
COPY workers/preprocess/requirements.txt /app/requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Copy the entire shared folder
COPY shared/ /app/shared/

# Copy the worker code
COPY workers/preprocess/preprocess_worker.py /app/preprocess_worker.py
COPY workers/preprocess/PreProcessingFlow.py /app/PreProcessingFlow.py

# Set environment variables
ENV PYTHONUNBUFFERED=1
ENV PYTHONPATH="/app:/shared"

CMD ["rq", "worker", "-u", "redis://redis:6379", "preprocess"]